# Detect changes on /schedule/images/*
# when changed, docker build schedule/images/pandas, docker push datacoves/airflow-pandas..

name: Test and Check on Pull Request

on:
  push:
    branches:
      - main
    paths:
      - "schedule/images/pandas/*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Image build and push

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKERHUB_USER}}
          password: ${{env.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: schedule/images/pandas
          push: true
          tags: datacoves/airflow-pandas:latest
